# ============================================
# Базовый шаблон (Dev + Prod)
# ============================================
x-base-settings: &base-settings
  build:
    context: .
    args:
      USER_ID: ${USER_ID:-1000}
      GROUP_ID: ${GROUP_ID:-1000}
      USERNAME: ${USERNAME:-user}
  volumes:
    - ./workspace:/workspace
    - ./.docker/nvim:/home/${USERNAME}/.config/nvim
    - f5tts-home:/home/${USERNAME}
  ports:
    - "8000:8000"
  env_file:
    - .env
  tty: true
  stdin_open: true

services:
  # ============================================
  # Основной сервис разработки (Dev Container)
  # ============================================
  f5tts-web-app:
    <<: *base-settings
    profiles: ["cpu"]
    container_name: f5tts_fastapi_dev_conteiner
    hostname: f5tts_fastapi_dev_conteiner
    volumes:
      - ./workspace:/workspace
      - ./.docker/nvim:/home/${USERNAME}/.config/nvim
      - f5tts-home:/home/${USERNAME}
      - /mnt/MyDownloads/000temp/localization_KCD2/workspace/models/:/workspace/models
    # command: poetry run python src/main.py
    command: zsh

  # ============================================
  # Prod Container
  # ============================================
  f5tts-web-app_gpu:
    <<: *base-settings
    profiles: ["cuda"]
    container_name: f5tts_fastapi_prod_container
    hostname: f5tts_fastapi_prod_container
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all # или укажите 1, 2 и т.д.
              capabilities: [gpu]
    command: poetry run python src/main.py

# ============================================
# Тома для сохранения данных
# ============================================
volumes:
  f5tts-home:
